#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define DLG_MAIN 100

#define EDIT_MAP_PATH 201
#define EDIT_MAP_WIDTH 202
#define EDIT_MAP_HEIGHT 203
#define EDIT_PARAM 204
#define EDIT_WORKINGDIR 205
#define BUTTON_CREATE_MAP 301
#define BUTTON_LOAD_MAP 302
#define BUTTON_SAVE_MAP 303
#define BUTTON_PERSIST_PARAM 304
#define BUTTON_RELOAD_PARAM 305
#define BUTTON_USE_TEXTURE 306
#define BUTTON_REFRESH_MAPS 307
#define BUTTON_UPDATE_WORKINGDIR 308
#define LIST_MAPS 401
#define LIST_PARAMETERS 402
